config/routes.rb
Dwellings::Application.routes.draw do

  root "sessions#new"
  post "/login" => "sessions#create", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  get "/groups/:group_id/bills" => "bills#new", as: "new_group_bill"
  get "/groups/:group_id/recipient/:recipient_id/payments" => "payments#new", as: "new_group_recipient_payment"
  post "/groups/:group_id/bills" => "bills#create", as: "group_bills"
  post "/groups/:group_id/recipient/:recipient_id/payments" => "payments#create", as: "group_recipient_payments"


  get "/groups/:group_id/member/:member_id/transactions" => "transactions#show", as: "member_transaction_history"


  resources :groups, except: [:index] do
    resources :comments, only: [:new, :create, :show]
    resources :transactions, only: [:edit, :delete, :show] do
      resources :comments, only: [:new, :create, :show]
    end
  end

  resources :users, only: [:new, :create, :show]
  post '/groups/:group_id/user/:user_id' =>  'users#leave', as: 'leave_group'

end

app/models/household.rb
class Household < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :comments, as: :commentable

  validates :name, presence:true
  validates :address, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  helper_method :current_user, :logged_in?

  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !(session[:user_id].nil?)
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def new
    group = Group.find_by_id(params[:group_id])
    @group_members = group.users - [current_user]
  end

  def create
    group = Group.find_by_id(params[:group_id])
    amount = params[:transaction_amount]

    if !params[:members]
      flash[:error] = "There was an issue creating the bill. Please select at least one member to bill."
    else
      params[:members].each do |key, email|

        user = User.find_by_email(email)
        b = Bill.new(
          from_user: current_user,
          to_user: user,
          group_id: group.id,
          amount: amount
        )

        if !b.save
          flash[:error] = "There was an issue creating the bill. Please enter a valid amount."
        end
      end
    end

    redirect_to group_path(group)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group= Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save && params[:users]
      @group.users << current_user
      rejects = @group.add_members(params["users"].values)
      unregistered_error(rejects) unless rejects.empty?
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def show
    @group = Group.find_by(id: params[:id])
    @members = @group.users - [current_user]
    @unconfirmed_txns = Transaction.where(to_user: current_user, confirmed: false)
  end

  def edit
    @group = Group.find_by(id: params[:id])
  end

  def update
    @group = Group.find_by(id: params[:id])
    if @group.update_attributes(group_params) && params[:users]
      rejects = @group.add_members(params["users"].values)
      unregistered_error(rejects) unless rejects.empty?
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :blurb)
  end
  def unregistered_error(rejects)
    flash[:error] = "The following emails are not registered members: #{rejects.join(", ")}"
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @group = Group.find_by_id(params[:group_id])
    @recipient = User.find_by_id(params[:recipient_id])
  end

  def create
    amount = params[:transaction_amount]
    group = Group.find_by_id(params[:group_id])
    recipient = User.find_by_id(params[:recipient_id])

    p = Payment.new(
      from_user: current_user,
      to_user: recipient,
      group_id: group.id,
      amount: amount
    )

    if !p.save
      flash[:error] = "There was an issue creating the payment. Please enter a valid amount."
    end

    redirect_to group_path(group)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:user_email] )
    if user && user.authenticate(params[:user_password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Invalid email or password"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def new
    if logged_in?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def edit
    transaction = Transaction.find_by_id(params[:id])
    transaction.update(confirmed: true)
    transaction.save
    redirect_to group_path(params[:group_id])
  end

	def show
		@group = Group.find_by_id(params[:group_id])
    @member = User.find_by_id(params[:member_id])

    txns = Transaction.where("from_user_id = #{current_user.id} AND to_user_id = #{@member.id} OR from_user_id = #{@member.id} AND to_user_id = #{current_user.id}")

    @transactions = txns.order('created_at DESC')

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_if_not_logged_in, except: [:new, :create]

  def new
    if logged_in?
      redirect_to user_path(current_user)
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def show
    @groups = current_user.groups
  end

  def leave
    redirect_to root_path unless params["user_id"].to_i == session[:user_id].to_i
    group = Group.find_by(id: params["group_id"])
    user = current_user
    user.groups.delete(group)
    user.save
    redirect_to user_path(user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

  def redirect_if_not_logged_in
    redirect_to root_path unless logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/new.html.erb
<h1>New Billing</h1>

<%= form_tag group_bills_path do %>
  <% count = 0 %>

  <% @group_members.each do |member| %>
    <%= member.first_name %> <%= check_box_tag "members[#{count += 1}]", "#{member.email}" %>
  <% end %>

  <%= text_field_tag :transaction_amount, '', placeholder: "Amount" %>
  <div class='wrap-center'><%= submit_tag "Create Bill" %></div>
<% end %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.text_field :name, placeholder: "Group name" %>
  <%= f.text_field :blurb, placeholder: "Blurb" %>
  <div class='wrap-center' id='add-member-container'><%= button_tag "Add member", id: "add-member", type: 'button' %></div>
  <div class='wrap-center'><%= f.submit %></div>
<% end %>

<% if @group.errors.any? %>
  <% @group.errors.full_messages.each do |msg| %>
    <div class='wrap-center'><p class='error'> <%= msg %> </p></div>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit <%= "#{@group.name}" %></h1>
<%= render 'form' %>

<br>
<br>
<br>
<div class='wrap-center'>
  <%= link_to 'Leave Group', leave_group_path(@group, current_user), method: "post", confirm: "Are you sure?", class: 'link danger' %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>
<%= render 'form' %>

app/views/groups/show.html.erb
<% if flash[:error] %>
  <div class='wrap-center'><p class='error'><%= flash[:error] %></p></div>
<% end %>

<div class='wrap-center'><h5><%= link_to "Edit Group", edit_group_path(@group), class: 'link' %></h5></div>

<h1> <%= @group.name %> </h1>
<h2> <%= @group.blurb %> </h2>


<br>
<div class='wrap-center'><%= link_to "Create Bill", new_group_bill_path(@group), class: 'link pay', id:"money" %></div>
<br>

<% @members.each do |member| %>
  <div class="member">
    <h3><%= member.full_name %></h3>
    <%= link_to "Pay", new_group_recipient_payment_path(@group, member), class: "pay link", id:"money" %>
    <%= link_to "Payment History", member_transaction_history_path(@group, member), class: "transactions link" %>
  </div>
<% end %>


<%= render 'transactions/unconfirmed_list' %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "Hi, #{current_user.first_name}!", "#" %>
    <%= link_to "My Profile", user_path(current_user) %>
    <%= link_to "Logout", logout_path, method: :delete %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groups</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= render 'layouts/header' %>
  <% end %>
  <div id="app-container">
    <%= yield %>
  </div>

</body>
</html>

app/views/payments/new.html.erb
<h1>New Payment to <%= @recipient.full_name %></h1>

<%= form_tag group_recipient_payments_path do %>

  <%= text_field_tag :transaction_amount, '', placeholder: "Amount" %>
  <div class='wrap-center'><%= submit_tag "Create Payment" %></div>
<% end %>

app/views/transactions/_unconfirmed_list.html.erb
<ul>
  <% @unconfirmed_txns.each do |txn| %>
    <li>
      <%= txn.transaction_type %> from <%= txn.from_user.full_name %>
      <br>
      $<%= txn.amount %>
      <br>
      <%= link_to "Confirm Transaction", edit_group_transaction_path(@group, txn) %>
    </li>
  <% end %>
</ul>

app/views/transactions/new.html.erb
<h1>New Billing</h1>

<%= form_tag group_transactions_path do %>
  <% count = 0 %>

  <% @group_members.each do |member| %>
    <%= member.first_name %> <%= check_box_tag "members[#{count += 1}]", "#{member.email}" %>
  <% end %>

  <%= text_field_tag :transaction_amount, '', placeholder: "Amount" %>
  <div class='wrap-center'><%= submit_tag "Create Bill" %></div>
<% end %>

app/views/transactions/show.html.erb
<!-- <h1>Transactions History for <%= @member.full_name %></h1> -->


<div class="wrap-center">


<h2>Transactions with <%= @member.full_name %> </h2>

<table>
    <tr>
      <th>Id</th>
      <th>Amount</th>
      <th>Transaction Type</th>
      <th>Created At</th>
    </tr>

	<% @transactions.each do |txn| %>

	<tr>
		<td><%= txn.id %></td>	
		<td><%= txn.amount %></td>	
		<td><%= txn.transaction_type %></td>	
		<td><%= txn.created_at %></td>	
	</tr>

	<% end %>	
</table>

</div>

app/views/users/new.html.erb
<h1>Register</h1>



<%= form_for @user do |f| %>
  <%= f.text_field :email, placeholder: "email" %>
  <%= f.text_field :first_name, placeholder: "first name" %>
  <%= f.text_field :last_name, placeholder: "last name"%>
  <%= f.password_field :password, placeholder: "password" %>
  <%= f.password_field :password_confirmation, placeholder: "confirm password"%>
  <div class='wrap-center'><%= f.submit "Register" %></div>
<% end %>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class='wrap-center'><p class = 'error'> <%= msg %></p></div>
    <% end %>
<% end %>

app/views/users/show.html.erb
<div class='wrap-center'><%= link_to "Create group", new_group_path, class: "link" %></div>

<div class='wrap-center' id="group-list">
  <ul>
    <% @groups.each do |group| %>
      <%= link_to group_path(group), class: 'ul-link' do %>
        <li>
          <h2><%= "#{group.name}" %></h2>
          <%= "#{group.blurb}" %>
        </li>
        <br>
      <% end %>
    <% end %>
  </ul>
</div>